Cache permissionset on user to avoid redundant lookups
Cadasta/django-tutelary pull request #36
Opened 2017-08-06 05:36 UTC by alukach

When accessing `/api/v1/organizations/cadasta/projects/london-2/resources/?limit=50` on my dev machine (with 1200 resources added to the project), I noticed that the API response was very slow (67s).  Using Django Debug Toolbar, I noticed that there were 7210 db queries:

![image](https://user-images.githubusercontent.com/897290/29000811-0d415d16-7a35-11e7-97e7-00dd567ba3e0.png)

Looking at the queries, I can see that 7200 of these queries are the same query:

![image](https://user-images.githubusercontent.com/897290/29000831-8c8f0df2-7a35-11e7-8e3b-7fc9b9d8eb6d.png)

This PR caches the first related `PermissionSet` on the requesting `User` instance if one does not exist and uses that cached value if the cache is already set.

The same API request now returns in 2.2s (the majority of the time spent rendering the browsable API form, using `?format=json` returns a response in about 700ms), requiring just 11 db queries.

2017-08-14 11:42 UTC, oliverroick requested changes
Can you look into why the tests are failing now?

2017-08-15 01:07 UTC, alukach commented
@oliverroick okay, we should be good now.

2017-08-28 13:40 UTC, oliverroick reviewed
The code looks ok. But we should test this against the platform code as well. Should I make an alpha release to pypi from this branch so you can the tests on cadasta-platform and open a PR with the upgraded dependencies?

2017-08-29 15:44 UTC, amplifi commented
@oliverroick Sounds good. Let's get this up on staging as soon as the sprint release is ready to go -- could significantly improve stability in the demo environment while we're finishing up tutelary replacement and superuser tools.

2017-09-06 15:04 UTC, amplifi approved these changes

2017-09-07 10:57 UTC, oliverroick approved these changes
The changes look ok.

I've created an alpha release and a branch ([`tutelary-0.1.22`](https://github.com/Cadasta/cadasta-platform/compare/tutelary-0.1.22)) to run tests against the release and  [some tests break now](https://travis-ci.org/Cadasta/cadasta-platform/builds/272846871). 

I managed to fix the tests by adding `del user.permset_tree` but it seems it requires a bit more work on the platform side. At least we should test whether updated permissions are displayed correctly in views related to permissions management or we need to delete the permission-set tree in these views.

2017-12-06 05:58 UTC, alukach commented
> "There are only two hard things in Computer Science: cache invalidation and naming things." - Phil Karlton



It seems that this PR has run into the first hard thing in CS.  I wanted to automatically cache the permission set tree on the user whenever the tree was first retrieved, thinking that the user instances were so short lived in memory that we wouldn't ever have to worry about invalidating the tree.  However, seeing tests like the following made me realize that there'd be problems around the idea:

```py
    def test_add_admin_role(self):
        assert self.user.has_perm('org.update', self.org) is False
        role = self._get_role()
        role.admin = True
        role.save()
        assert self.user.has_perm('org.update', self.org) is True
```

I thought about adding signal handlers for any time a `Role` was created to delete the cache from the `user` instance (if available) but that proved overly difficult being that often the user was not available and we'd have to listen to signals for many models (`Role`, `PermissionSet`, `Policy` `PolicyInstance`, `RolePolicyAssign`, etc).

In the end, it seemed like a simpler way to achieve our optimization goals was to allow us to opt-in to caching the permission tree when needed (namely, in the `check_perms` function used by all of the Tutelary mixins).

Fun fact: this change makes the Tutelary tests run in 55% of the time.

2017-12-06 14:44 UTC, oliverroick approved these changes
This looks about right. Ran the platform tests against this branch and it works fine. Good work!

2017-12-06 16:37 UTC, merged